blog_homepage:
    path:     /blog
    defaults: { _controller: BlogBundle:Default:index }
blog_post:
    path: /blog/{id}
    defaults: { _controller: BlogBundle:Default:post}
blog_create_post:
    path: /blog/admin/create
    defaults: { _controller: BlogBundle:Default:createPost}
blog_posts:
    path: /blog/admin/posts
    defaults: { _controller: BlogBundle:Default:posts}
blog_update_post:
    path: /blog/admin/update/{id}
    defaults: { _controller: BlogBundle:Default:updatePost}
blog_delete_post:
    path: /blog/admin/delete/{id}
    defaults: { _controller: BlogBundle:Default:deletePost}


